version: '3.3'

services:
  socat:
    image: rancher/socat-docker
    networks:
      - net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    logging:
      driver: json-file
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.10'
          memory: 8M
        reservations:
          cpus: '0.10'
          memory: 8M

  proxy:
    image: traefik:1.6.2
    command: 
    - "--api"
    - "--accesslog"
    - "--traefiklog"
    - "--entrypoints=Name:http Address::80 Redirect.EntryPoint:https Compress:true"
    - "--entrypoints=Name:https Address::443 TLS Compress:true"
    - "--defaultentrypoints=http,https"
    - "--acme"
    - "--acme.storage=/etc/traefik/acme.json"
    - "--acme.entryPoint=https"
    - "--acme.httpChallenge.entryPoint=http"
    - "--acme.acmeLogging=true"
    - "--acme.caServer=https://acme-staging-v02.api.letsencrypt.org/directory"
    - "--acme.onHostRule=true"
    - "--acme.onDemand=false"
    - "--acme.email=admin+letsencrypt@topmonks.com"
    - "--acme.domains=*.dev.tmcloud.io,dev.tmcloud.io"
    - "--acme.dnsChallenge"
    - "--acme.dnsChallenge.provider=route53"
    - "--acme.dnsChallenge.delayBeforeCheck=180"
    - "--docker"
    - "--docker.swarmMode"
    - "--docker.endpoint=tcp://socat:2375"
    - "--docker.exposedByDefault=false"
    - "--docker.domain=aws.tmcloud.io"
    - "--docker.watch"
    environment:
     AWS_ACCESS_KEY_ID: "AKIAJAJFUNLHT2MRW3PQ"
     AWS_SECRET_ACCESS_KEY: "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"
     AWS_REGION: "us-east-1"
    volumes:
      - etc:/etc/traefik
    networks:
      - net
      - proxy_net
    ports:
      - "80:80"
      - "443:443"
      - 8080:8080
    logging:
      driver: json-file
    deploy:
      placement:
        constraints:
          - node.role == worker
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
        
volumes:
  etc:
    driver: cloudstor:aws
    driver_opts: 
      filemode: "0600"
      
networks:
  net:
    driver: overlay
  proxy_net:
    external: true
